server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dock_dorsal_system
    username: postgres
    password: ionic
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true